[build-system]
requires = ["meson-python", "meson[ninja]", "Cython"]
build-backend = "mesonpy"

[project]
name = "llnl-hatchet"
description = "A Python library for analyzing hierarchical performance data"
dynamic = ["version"]
readme = "./README.md"
license = { file="LICENSE" }
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "License :: OSI Approved :: MIT License",
]
authors = [
  { name = "Abhinav Bhatele", email = "bhatele@cs.umd.edu" },
  { name = "Stephanie Brink", email = "brink2@llnl.gov" },
  { name = "Todd Gamblin", email = "tgamblin@llnl.gov" }
]
maintainers = [
  { name = "Olga Pearce", email = "pearce8@llnl.gov" },
  { name = "Ian Lumsden", email = "ilumsden@vols.utk.edu" },
  { name = "Connor Scully-Allison", email = "cscullyallison@sci.utah.edu" },
  { name = "Dewi Yokelson", email = "dewiy@cs.uoregon.edu" },
  { name = "Michael McKinsey", email = "michaelmckinsey@tamu.edu" }
]
requires-python = ">= 3.7"
dependencies = [
  "pydot",
  "PyYAML",
  "matplotlib",
  "numpy",
  "pandas",
  "textX >= 3.0.0",
  "multiprocess",
  "caliper-reader",
]

[project.urls]
source_code = "https://github.com/llnl/hatchet"
documentation = "https://llnl-hatchet.readthedocs.io/en/latest/"

[project.optional-dependencies]
hdf_writer = [
  "tables"
]

[tool.ruff]
line-length = 88
target-version = 'py39'
include = ['\.pyi?$']
exclude = [
  ".eggs",
  ".git",
  ".hg",
  ".mypy_cache",
  ".tox",
  ".venv",
  "_build",
  "buck-out",
  "build",
  "dist",
]

[tool.black]
line-length = 88
target-version = ['py35', 'py36', 'py37', 'py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
